# NumPy Lab Exercises 

Solve the following questions in Lab to test your knowledge on NumPy Package!

#### Import NumPy package as np

In [3]:
import numpy as np

#### Create an array of 20 0's 

In [5]:
a=np.zeros(20)
a[2]=5
a

array([0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 20 1's

In [5]:
array_master = np.ones(20)
array_copy = array_master.copy()
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

#### Create an array containing 30 sixes

In [8]:
array_me = np.ones(30)
array_me[:] =6
array_me

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

#### Create an array of integers starting from 21 until 31

In [10]:
array_one = np.arange(21,32)
array_one

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

#### Create an array of all even integers from 2 to 60

In [11]:
array_two = np.arange(2,62,2)
array_two

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

#### Create a 5x6 matrix with values ranging from 0 to 29

In [12]:
array_matrix = np.arange(30).reshape(5,6)
array_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### Create an identity matrix of shape 5x5

In [17]:
array_i = np.eye(3)
array_i
array_i[array_i == 0] = 21
array_i

array([[ 1., 21., 21.],
       [21.,  1., 21.],
       [21., 21.,  1.]])

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

In [21]:
array_random = np.random.rand(10)
array_random


array([0.60740163, 0.05469019, 0.23363385, 0.91208555, 0.55282767,
       0.66395833, 0.84742444, 0.21945862, 0.36764355, 0.70992642])

#### Use NumPy to generate an array of 15 random numbers sampled from a standard normal distribution

In [24]:
array_randomn = np.random.randn(15)
array_randomn

array([ 0.84597518, -0.12339658,  0.36141981, -0.76776992,  1.09094807,
        0.41915618,  0.0087355 ,  0.30209302,  0.69349988,  1.82624376,
        0.65954063, -0.16393054, -1.04319765,  0.6298406 ,  0.69340977])

##### Create the following 5x10 matrix with the values using arange,reshape and arithmetic operators:

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ]])

#### Create an array of 30 linearly spaced points between 0 and 10:

In [25]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

## Numpy Indexing and Selections

Using the below given Matrix, generate the output for the below questions

In [27]:
simple_matrix = np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [28]:
simple_matrix[8:,0:3]

array([[81, 82, 83],
       [91, 92, 93]])

#### Retrieve the value 55 from the above matrix using index & selection technique

In [34]:
simple_matrix[5,4]

55

#### Retrieve the values from the 3rd column in the above matrix

In [36]:
simple_matrix[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

#### Retrieve the values from the 4th row in the above matrix

In [37]:
simple_matrix[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

#### Retrieve values from the 2nd & 4th rows in the above matrix

In [38]:
simple_matrix[(1,3),:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

### Calculate the following values for the given matrix

#### Calculate sum of all the values in the matrix

In [39]:
simple_matrix.sum()

5050

#### Calculate standard deviation of all the values in the matrix

In [42]:
simple_matrix.std()

28.86607004772212

#### Calculate the variance of all values in the matrix

In [43]:
simple_matrix.var()

833.25

#### Calculate the mean of all values in the matrix

In [44]:
simple_matrix.mean()

50.5

### End of Lab Exercise - NumPy